info:
  app:
    name: Pivotal Credential Manager
    version: ${buildVersion}
security:
  oauth2:
    resource:
      id: credhub
  basic:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: validate
