info:
  app:
    name: CredHub
    version: ${buildVersion}

security:
  oauth2:
    resource:
      id: credhub
  basic:
    enabled: false
  authorization:
    acls:
      enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: validate
