auth_server:
  # Public dummy UAA for local development usage only!
  # Username/password: credhub/password
  url: https://34.206.233.195:8443


security:
  oauth2:
    enabled: true
    resource:
      jwk:
        key-set-uri: https://34.206.233.195:8443/token_keys
