---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfseceng/credhub-unit-tests

inputs:
  - name: sec-eng-credential-manager

run:
  path: sec-eng-credential-manager/ci/tasks/unit-tests/task.sh

params:
  DATABASE_PROFILE:
